# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7815fc6ad7f43fec803dbe297275ace25e2fe436a06e5010edaeccfc9f406689bdc5b68c373047a54fbaf51238cb6221e00a378ba070136bdcece9237157c4d7

test:
  secret_key_base: 50043dd9e492529eb99db1b566e67b460df4bcad16cebc816b49d678cda1056287fe93d611f998bc57f698cc1a672bd6dae1e0256efdd6dd837c6a36726a1264

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
